stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: registry.gitlab.com/huanle94/my-cv/${CICD_GIT_BRANCH}:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: registry.gitlab.com
    when:
      branch:
        include:
        - master
  when:
    branch:
      include:
      - master
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch:
        include:
        - master
  when:
    branch:
      include:
      - master
timeout: 60
notification: {}
