kind: Service
apiVersion: v1
metadata:
  name: mycv-service
spec:
  selector:
    app: mycv
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-mycv
  labels:
    app: mycv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycv
  template:
    metadata:
      labels:
        app: mycv
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: mycv
        image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}
        ports:
        - containerPort: 80